# TestCompile.yml
# Github workflow script to test compile all examples of an Arduino library repository.
#
# Copyright (C) 2020  Armin Joachimsmeyer
# https://github.com/ArminJo/Github-Actions
#

# This is the name of the workflow, visible on GitHub UI.
name: TestCompile
on: push
jobs:
  build:
    name: Test compiling examples for UNO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout custom library
        uses: actions/checkout@v2
        with:
          repository: ArminJo/Arduino-BlueDisplay
          ref: master
          path: CustomLibrary_BlueDisplay # must contain string "Custom"

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@master
        with:
          sketch-names: SimpleTouchScreenDSO.cpp
          build-properties: '{ "All": "-DUSE_SIMPLE_SERIAL" }'
#          required-libraries: BlueDisplay
